/**
 * Phase 19 — validation.ts pure-helper unit tests.
 *
 * Coverage (D-VAL-1, D-VAL-3, D-VAL-4):
 * 1. empty text → reason 'empty'
 * 2. whitespace-only text → reason 'empty'
 * 3. non-redacted, model name verbatim → ok
 * 4. non-redacted, model name absent → reason 'missing_model_name'
 * 5. non-redacted, paraphrased name (case-sensitive contract) → reason 'missing_model_name'
 * 6. non-redacted, multiple models — at least one matches → ok
 * 7. redacted=true, marker 'redacted' present → ok
 * 8. redacted=true, marker 'PARTIAL' uppercase → ok (case-insensitive)
 * 9. redacted=true, no marker → reason 'missing_redaction_marker'
 * 10. redacted=true, no models + marker → still ok (redacted skips model-name check)
 */

import { describe, expect, it } from 'vitest';
import { REDACTION_MARKERS, validateSummary } from '../validation.js';
import type { ModelRef } from '../../../types/provenance.js';

function model(name: string, node_id = '4'): ModelRef {
  return {
    node_id,
    class_type: 'CheckpointLoaderSimple',
    model_name: name,
    model_hash: null,
    model_hash_unavailable: null,
  };
}

describe('validateSummary — empty/whitespace short-circuit', () => {
  it('Test 1: empty text → reason "empty"', () => {
    expect(validateSummary('', [model('flux1-dev')], false)).toEqual({
      ok: false,
      reason: 'empty',
    });
  });

  it('Test 2: whitespace-only text → reason "empty"', () => {
    expect(validateSummary('   \n\t  ', [model('flux1-dev')], false)).toEqual({
      ok: false,
      reason: 'empty',
    });
  });
});

describe('validateSummary — non-redacted (D-VAL-1 case-sensitive verbatim model match)', () => {
  it('Test 3: model name appears verbatim → ok', () => {
    const text = 'v003 generated with flux1-dev at seed 42.';
    expect(validateSummary(text, [model('flux1-dev')], false)).toEqual({ ok: true });
  });

  it('Test 4: model name absent → reason "missing_model_name"', () => {
    const text = 'A nice version generated by an AI model at seed 42.';
    expect(validateSummary(text, [model('flux1-dev')], false)).toEqual({
      ok: false,
      reason: 'missing_model_name',
    });
  });

  it('Test 5: paraphrased model name (case-sensitive contract) — "Flux" vs "flux1-dev" → reason "missing_model_name"', () => {
    const text = 'v003 generated with Flux at seed 42.';
    expect(validateSummary(text, [model('flux1-dev')], false)).toEqual({
      ok: false,
      reason: 'missing_model_name',
    });
  });

  it('Test 6: multiple models — at least one matches → ok', () => {
    const text = 'v003 used cinematic_fantasy LoRA atop the base.';
    const result = validateSummary(
      text,
      [model('flux1-dev'), model('cinematic_fantasy', '10')],
      false,
    );
    expect(result).toEqual({ ok: true });
  });

  it('non-redacted, empty models array → reason "missing_model_name"', () => {
    const text = 'v003 generated at seed 42.';
    expect(validateSummary(text, [], false)).toEqual({
      ok: false,
      reason: 'missing_model_name',
    });
  });

  it('non-redacted, model with empty name string is skipped', () => {
    const text = 'v003 generated at seed 42.';
    expect(
      validateSummary(text, [model(''), model('flux1-dev')], false),
    ).toEqual({ ok: false, reason: 'missing_model_name' });
    expect(
      validateSummary('flux1-dev was used.', [model(''), model('flux1-dev')], false),
    ).toEqual({ ok: true });
  });
});

describe('validateSummary — redacted (D-VAL-3 case-insensitive marker)', () => {
  it('Test 7: marker "redacted" present → ok', () => {
    const text = 'v003 had some prompt fields redacted before re-signing.';
    expect(validateSummary(text, [], true)).toEqual({ ok: true });
  });

  it('Test 8: marker "PARTIAL" uppercase → ok (case-insensitive)', () => {
    const text = 'v003 was a PARTIAL re-sign — manifest invalidated.';
    expect(validateSummary(text, [], true)).toEqual({ ok: true });
  });

  it('marker "Redaction" mixed-case → ok', () => {
    const text = 'A Redaction was applied to this version.';
    expect(validateSummary(text, [], true)).toEqual({ ok: true });
  });

  it('Test 9: no marker present → reason "missing_redaction_marker"', () => {
    const text = 'v003 generated with flux1-dev at seed 42.';
    expect(validateSummary(text, [model('flux1-dev')], true)).toEqual({
      ok: false,
      reason: 'missing_redaction_marker',
    });
  });

  it('Test 10: redacted=true with no models + marker → ok (model-name check skipped)', () => {
    const text = 'Some fields were redacted.';
    expect(validateSummary(text, [], true)).toEqual({ ok: true });
  });
});

describe('REDACTION_MARKERS export', () => {
  it('exposes the 3 markers documented in D-VAL-3', () => {
    expect(REDACTION_MARKERS).toEqual(['redacted', 'partial', 'redaction']);
  });
});
